apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    proj: roboshop
    env: test
    app: nginx
spec:
  type: ClusterIP
  selector:
    matchlabels:
      proj: roboshop
      env: test
      app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
