apiVersion: v1
kind: deployment
metadata:
  name: resourcemgmt-ex-deployment
  replicas: 2
  namespace: roboshop
  labels:
    proj: roboshop
    env: test
    app: nginx
spec:
  containers:
  - name: resourcemgmt-ex-container
    image: nginx
    resources:
      requests:
        memory: "4Mi"
        cpu: "25m"
      limits:
        memory: "12Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: app-config